AllCops:
  Exclude:
    - vendor/**/*
    - db/**/*
    - config/**/*
    - specs/**/*

Metrics/MethodLength:
  Enable: False

Metrics/MethodLength:
  Enable: False

Metrics/LengthClass:
  Enable: False

